on:
  workflow_call:
    secrets:
      token:
        required: true
      docker_username:
        required: false  # Optional, only required if Docker login is needed
      docker_password:
        required: false  # Optional, only required if Docker login is needed
      docker_url:
        required: false  # Optional, only required if Docker login is needed
    inputs:
      docker_url:
        type: string
        required: false
  
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: go

  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false

      # Conditionally login to Docker
      - name: Login to docker
        if: ${{ inputs.docker_url }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_url }}
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
